import { brand } from "@/lib/brand";
import type { FormDefinition } from "./schema";

export const volunteerForm: FormDefinition = {
  slug: "volunteer",
  title: "Serve with us",
  description: "Tell us where you’d love to help — we’ll follow up.",
  active: true,
  pco: {
    source: "Website — Volunteer Form",
    stage: "Volunteer Interest",
    includeAnswers: true,
  },
  success: {
    title: "Thank you for offering to serve",
    body: "Your willingness matters. A ministry lead will reach out soon with next steps.",
    secondary: `${brand.service.when} · La Habra`,
    ctaLabel: "Back to 1128",
    ctaHref: brand.siteUrl,
    personalizeWithName: true,
  },
  email: {
    subject: "Thanks for offering to serve at 1128",
    preview: "Thanks for offering to serve at 1128.",
    heading: "Thank you, {{firstName}}.",
    body: [
      "We’re grateful you want to serve with us. A ministry lead will follow up soon with next steps and how to get plugged in.",
      "Until then — come worship with us Sunday at 11:45 AM.",
    ],
    ctaLabel: "Visit 1128",
    ctaHref: brand.siteUrl,
    footer: `${brand.legalName} · La Habra, CA`,
  },
  steps: [
    {
      id: "welcome",
      type: "statement",
      title: "Serve with 1128",
      body: "We reflect God’s love by serving one another. A few questions and we’ll connect you with the right team.",
    },
    {
      id: "first_name",
      type: "name",
      role: "first_name",
      title: "First name?",
      placeholder: "Type your answer here…",
      required: true,
    },
    {
      id: "last_name",
      type: "name",
      role: "last_name",
      title: "Last name?",
      placeholder: "Type your answer here…",
      required: true,
    },
    {
      id: "email",
      type: "email",
      role: "email",
      title: "Email?",
      placeholder: "name@email.com",
      required: true,
    },
    {
      id: "phone",
      type: "phone",
      role: "phone",
      title: "Phone?",
      placeholder: "(555) 555-5555",
      required: false,
    },
    {
      id: "areas",
      type: "multi_choice",
      title: "Where would you like to serve?",
      help: "Pick as many as you want.",
      required: true,
      options: [
        { value: "worship", label: "Worship / band" },
        { value: "production", label: "Production / tech" },
        { value: "hospitality", label: "Hospitality / welcome" },
        { value: "kids", label: "Kids ministry" },
        { value: "prayer", label: "Prayer ministry" },
        { value: "setup", label: "Setup / teardown" },
        { value: "other", label: "Wherever there’s need" },
      ],
    },
    {
      id: "experience",
      type: "yes_no",
      title: "Have you served on a church team before?",
      required: true,
      autoAdvance: true,
      options: [
        { value: "yes", label: "Yes" },
        { value: "no", label: "Not yet" },
      ],
    },
    {
      id: "availability",
      type: "single_choice",
      title: "When are you usually available?",
      required: true,
      autoAdvance: true,
      options: [
        { value: "sunday_am", label: "Sunday mornings" },
        { value: "weekday", label: "Weekdays" },
        { value: "flexible", label: "Pretty flexible" },
      ],
    },
    {
      id: "notes",
      type: "long_text",
      role: "notes",
      title: "Anything else we should know?",
      help: "Gifts, experience, questions — optional.",
      placeholder: "Type here…",
      required: false,
    },
  ],
};
